version: '2'
services:
  server:
    build: .
    volumes:
      - "./:/app"
    environment:
      - DATABASE_URL=postgres://dbuser:dbpw@database:5432/dbname
      - DOMAIN=http://localhost:2000
      - PORT=2000
    ports:
      - "2000:2000"
    links:
      - database
    command: yarn run development
  database:
    image: postgres:9.6.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpw
      - POSTGRES_DB=dbname
